apiVersion: v1
kind: Namespace   # Namespace is a resource in Kubernetes that is used to divide the cluster into multiple virtual clusters. It is a way to divide cluster resources between multiple users (via resource quota).
metadata:
  name: expense
  labels:
    name: expense
    environment: dev
