kind: Pod      # Pod is a resource in Kubernetes that is used to run a single instance of an application. It is the smallest and simplest unit in the Kubernetes object model that you create or deploy.
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx

