kind: Pod
apiVersion: v1
metadata:
  name: multi-container    # multi containers in a single pod
spec:
  containers:
  - name: nginx
    image: nginx
  - name: alma
    image: "almalinux:9"
    command: ["sleep","2000"]