apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: k8
    trainee: Sandeep
  annotations:
    kubernetes.io/created-by: 'sandeep'
    jenkins.build.url: 'https://jenkins.devops91.cloud/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx