apiVersion: v1
kind: Pod
metadata:
  name: annotations     # annotations are key-value pairs that can be attached to objects, such as pods. Annotations are intended to be small or large pieces of unstructured data, and can be more complex than labels, including structured fields and arbitrary subobjects.
  labels:
    course: k8
    trainee: Sandeep
  annotations:
    kubernetes.io/created-by: 'sandeep'
    jenkins.build.url: 'https://jenkins.devops91.cloud/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx