apiVersion: v1
kind: Pod
metadata:
  name: resourse
spec:
  containers:
  - name: nginx
    image: nginx
    resourse:
      #soft limit
      requests:
        cpu: "100m"
        memory: "128Mi"
      # limits should be atleast or more than requests i.e hard limit
      limits:
        cpu: "100m"
        memory: "128Mi"

