apiVersion: v1
kind: ConfigMap    # ConfigMap is a resource in Kubernetes that is used to store non-confidential data in key-value pairs. It is used to store configuration data in the form of key-value pairs.
metadata:
  name: devops91
data:
  course: "DevOps"
  trainer: "Siva"
  github: "https://github.com/sandeepnaianala/learn-kubernetes"
