apiVersion: v1
kind: pod
metadata:
  name: pod-config     # ConfigMap in a pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:      # ConfigMap in a pod
        name: devops91
    #env:
    #- name: course
    # ValueFrom:
    #    configMapKeyRef:
    #     name: devops91
    #     key: course
    #- name: trainer
    #  ValueFrom:
    #   configMapKeyRef:
    #     name: devops91
    #     key: trainer
