apiVersion: v1
kind: Secret      # Secret in a pod is used to store sensitive data like passwords, OAuth tokens, and ssh keys. It is stored in base64 encoded format.
metadata:
  name: pod-secret
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"