apiVersion: v1
kind: Pod
metadata:
  name: pod-secret1     # secret in a pod is used to store sensitive data
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:           # secret in a pod
    - secretKeyRef:
        name: pod-secret