apiVersion: v1
kind: Service      # Service is used to expose the application to the outside world or to other services in the cluster. It is a way to decouple the application from the environment.
metadata:
  name: service
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80     #service-port
    targetPort: 80 # target-port