apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer      # LoadBalancer service type is used to expose the service outside the cluster using the cloud provider's load balancer.
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
    nodePort: 32761