kind: Deployment   # Deployment is used to deploy applications in kubernetes cluster. It is a way to manage the application lifecycle.
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  # pod definition
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx