apiVersion: v1
kind: Secret
metadata:
  name : secret01
data:
# used coverter base64 from text example: example.com
  URL: ZXhhbXBsZS5jb20=
  SUB_URL: c3ViLmV4YW1wbGUuY29t
  DOMAIN: LmNvbQ==

---
apiVersion: v1
kind: pod
metadata:
  name: nginx06
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: secret01