apiVersion: v1
kind: deploy
metadata:
  name: nginx
  lables:
    app: nginx
    tire: frontend
spec:
  replicas: 3
  selector:
    matchlabels:
      tire: frontend
      app: nginx
  template:
    metadata:
      labels:
        tire: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cip
spec:
  selector:
    tire: frontned
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetport: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    tire: frontned
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetport: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: LoadBalancer
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80