apiVersion: v1
kind: PersistentVolume     # PersistentVolume is a piece of storage in the cluster that has been provisioned by an administrator or dynamically provisioned using Storage Classes.
metadata:
  name: ebs-pv
spec:
  accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    csi:
      driver: ebs.csi.aws.com
      fsType: ext4
      volumeHandle: vol-0a8f7b7b7b7b7b7b7     # volumeHandle is the volume ID of the EBS volume that you want to use.

-------
apiVersion: v1
kind: PersistentVolumeClaim     # PersistentVolumeClaim is a request for storage by a user.
metadata:
  name: ebs-static
spec:
   storageClassName: ""    # storageClassName is the name of the StorageClass that you want to use.
   volumeName: ebs-static
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi

------
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim